# Generated by Django 6.0.4 on 2026-04-21 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("display_name", models.CharField(max_length=50)),
                ("bio", models.TextField(blank=True)),
                ("profile_link", models.URLField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Flyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.CharField(max_length=50)),
                ("flyer_name", models.CharField(max_length=50)),
                ("event_name", models.CharField(blank=True, max_length=50)),
                ("event_date", models.DateField()),
                ("event_location", models.CharField(max_length=100)),
                (
                    "cover_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("event_link", models.URLField(blank=True)),
                (
                    "flyer_image",
                    models.ImageField(blank=True, null=True, upload_to="flyers/"),
                ),
                (
                    "background_color",
                    models.CharField(default="#000000", max_length=20),
                ),
                ("font_color", models.CharField(default="#FFFFFF", max_length=20)),
                ("font_family", models.CharField(default="Arial", max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flyers",
                        to="flyer_app.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["event_date", "flyer_name"],
            },
        ),
    ]
