# Generated by Django 6.0.4 on 2026-04-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flyer_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flyer",
            name="background_color",
            field=models.CharField(
                choices=[
                    ("#000000", "Black"),
                    ("#FFFFFF", "White"),
                    ("#212529", "Dark Gray"),
                    ("#F8F9FA", "Light Gray"),
                    ("#DC3545", "Red"),
                    ("#0D6EFD", "Blue"),
                    ("#198754", "Green"),
                    ("#FFC107", "Gold"),
                    ("#6F42C1", "Purple"),
                ],
                default="#000000",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flyer",
            name="font_color",
            field=models.CharField(
                choices=[
                    ("#FFFFFF", "White"),
                    ("#000000", "Black"),
                    ("#DC3545", "Red"),
                    ("#0D6EFD", "Blue"),
                    ("#198754", "Green"),
                    ("#FFC107", "Gold"),
                    ("#6F42C1", "Purple"),
                ],
                default="#FFFFFF",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flyer",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("Arial", "Arial"),
                    ("Georgia", "Georgia"),
                    ("Impact", "Impact"),
                    ("Times New Roman", "Times New Roman"),
                    ("Verdana", "Verdana"),
                    ("Courier New", "Courier New"),
                ],
                default="Arial",
                max_length=50,
            ),
        ),
    ]
