# Generated by Django 6.0.4 on 2026-05-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flyer_app",
            "0002_alter_flyer_background_color_alter_flyer_font_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="flyer",
            name="background_color",
            field=models.CharField(
                choices=[
                    ("#2b241f", "Ivory Black"),
                    ("#e2dfd7", "Bone White"),
                    ("#f1a512", "Golden Orange"),
                    ("#dd4111", "Burnt Orange"),
                    ("#8c0027", "Oxblood"),
                    ("#2baf90", "Jungle Green"),
                    ("#a1d4b1", "Celadon"),
                ],
                default="#000000",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flyer",
            name="font_color",
            field=models.CharField(
                choices=[
                    ("#2b241f", "Ivory Black"),
                    ("#e2dfd7", "Bone White"),
                    ("#f1a512", "Golden Orange"),
                    ("#dd4111", "Burnt Orange"),
                    ("#8c0027", "Oxblood"),
                    ("#2baf90", "Jungle Green"),
                    ("#a1d4b1", "Celadon"),
                ],
                default="#FFFFFF",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flyer",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Lora", "Lora"),
                    ("Libre Baskerville", "Libre Baskerville"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Merriweather", "Merriweather"),
                    ("Cinzel", "Cinzel"),
                ],
                default="Arial",
                max_length=50,
            ),
        ),
    ]
