# Generated by Django 6.0.4 on 2026-05-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flyer_app",
            "0003_alter_flyer_background_color_alter_flyer_font_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="flyer",
            name="background_color",
            field=models.CharField(
                choices=[
                    ("#2b241f", "Worn"),
                    ("#e2dfd7", "Bone"),
                    ("#f1a512", "Cheese"),
                    ("#dd4111", "Rust"),
                    ("#8c0027", "Oxblood"),
                    ("#2baf90", "Island"),
                    ("#a1d4b1", "Sage"),
                ],
                default="#e2dfd7",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flyer",
            name="font_color",
            field=models.CharField(
                choices=[
                    ("#2b241f", "Worn"),
                    ("#e2dfd7", "Bone"),
                    ("#f1a512", "Cheese"),
                    ("#dd4111", "Rust"),
                    ("#8c0027", "Oxblood"),
                    ("#2baf90", "Island"),
                    ("#a1d4b1", "Sage"),
                ],
                default="#2b241f",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flyer",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("'Bebas Neue', sans-serif", "Default"),
                    ("'Climate Crisis', sans-serif", "Heavy"),
                    ("Crushed, sans-serif", "Retro"),
                    ("Lobster, cursive", "Script"),
                    ("'Playwrite NO', cursive", "Written"),
                    ("'Playwrite NZ Guides', cursive", "Sketched"),
                    ("'Syne Mono', monospace", "Type"),
                    ("'Unica One', sans-serif", "Poster"),
                ],
                default="Bebas Neue",
                max_length=50,
            ),
        ),
    ]
